### ISSUE TITLE
Schnittstelle für Pepper.

### ISSUE THREAD

**Issue by raeglan** [suturo16/planning#3]
Es wäre schön wenn ich aus Pepper's Communication auch Anweisungen zu Planning geben könnte. Das geht über ein Service oder auch ein Topic indem Pepper die infos packen kann.

**Comment by 4r7hur0** [comment]
Das Topic wird 'pepper_command' heißen und erwartet eine Nachricht im Format std_msgs/String. 
Bearbeitet in https://github.com/suturo16/planning/tree/pepper_command_interface

**Comment by cpollok** [comment]
Benutzt in Zukunft bitte Trello für die Issues. Dort kann man auch wunderbar Pull Request verlinken.
